http_archive(
    name = "io_bazel_rules_go",
    sha256 = "feba3278c13cde8d67e341a837f69a029f698d7a27ddbb2a202be7a10b22142a",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.10.3/rules_go-0.10.3.tar.gz",
)

# Fill in the fields below.
http_archive(
    name = "snippets",
    sha256 = "<checksum of source tarball>",
    strip_prefix = "snippets-<tag or commit>",
    url = "https://github.com/ProdriveTechnologies/snippets/archive/<tag or commit>.tar.gz",
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "6dede2c65ce86289969b907f343a1382d33c14fbce5e30dd17bb59bb55bb6593",
    strip_prefix = "rules_docker-0.4.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.4.0.tar.gz"],
)

load("@io_bazel_rules_docker//container:container.bzl", container_repositories = "repositories")

container_repositories()

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_repositories", "go_rules_dependencies")

go_register_toolchains()
